name: Guðfinnur
favicon: null
layout_spectrum: 0.17862278455868363
typography_spectrum: 0.7232862336095423
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8210854614153504
  lightness: 0.18915368034504354
  saturation: 0.5634269025176764
  rhythmicContrast: 0.4340055484790355
purpose: []
