name: Guðfinnur
favicon: null
layout_spectrum: 0.17862278455868363
typography_spectrum: 0.7232862336095423
title: Gudfinnur.is
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f7f5'
    - '#06070e'
    - '#b2b6b0'
    - '#eb4600'
    - '#0d565e'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.875
  rhythmicContrast: 0.4340055484790355
purpose: []
